apiVersion: apps/v1
kind: Deployment
metadata:
  name: telecomm-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: telecomm
  template:
    metadata:
      labels:
        app: telecomm
    spec:
      containers:
      - name: telecomm-container
        image: yogeshpatil/telecomm-app:1.0
        ports:
        - containerPort: 5000
